### ISSUE TITLE
Bind as another user

### ISSUE THREAD

**Issue by s0undt3ch** [zoldar/python-ldap-test#10]
I've provided an entry like:

```
        {
            'ou': ['Users'],
            'roomnumber': ['123'],
            'cn': ['Admin'],
            'gidNumber': [998],
            'sn': ['Admin'],
            'homeDirectory': ['/home/admin'],
            'uidNumber': ['998'],
            'userpassword': ['admin'],
            'mail': ['admin@example.com'],
            'uid': ['admin'],
            'givenname': ['Admin'],
            'objectclass': ['person', 'inetOrgPerson', 'organizationalPerson', 'posixAccount', 'top'],
            'dn': 'uid=admin,ou=Users,dc=example,dc=com',
        },
```

That's not the `bind_dn` nor the `password` provided in the `LdapServer` settings. I seem to be unable to bind using the above `db` and `userpassword`.

**Comment by zoldar** [comment]
@s0undt3ch I'll look into that when time permits :)

**Comment by s0undt3ch** [comment]
If I also find time, I'll try to hack it, although, I'm not a java guy...

Thanks!!!

**Comment by s0undt3ch** [comment]
I'm actually capable of binding as a different user now. Closing.

**Comment by levary** [comment]
@s0undt3ch Could you tell me, please, how exactly I can bind as another user?

**Comment by s0undt3ch** [comment]
I just added the users with password field set and it worked.

**Comment by vbo75** [comment]
@s0undt3ch Do you have an exemple ?
Thanks

**Comment by s0undt3ch** [comment]
I no longer have access to the project where I was using this, sorry.
