### ISSUE TITLE
Server starts immediately after a call to constructor

### ISSUE THREAD

**Issue by tvendelin** [zoldar/python-ldap-test#14]
Either there's something missing from the manual, or there is a bug. The server starts in the foreground immediately after LdapServer() object is constructed, and I cannot get any further. The same happens when the code is run as a script. 

```
Python 2.7.13 (default, Dec 18 2016, 05:35:35) 
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ldap_test import LdapServer
>>> server = LdapServer()
INFO:ldap_test:Starting the JavaGateway on python_proxy_port 25334
Gateway server started on port 25333!

```
I'm running it from python virtual environment on Mac OS X
System Version:	OS X 10.11.6 (15G1212)
Kernel Version:	Darwin 15.6.0

**Comment by nikogura** [comment]
I'm getting the same behavior.

The call:  self.builder = self.gateway.jvm.net.zoldar.ldap.testserver.LdapBuilder on line 123 of server.py just hangs.

This is a bridge point between the python and java code.  Something is not happy here.

**Comment by nikogura** [comment]
Introduced https://github.com/zoldar/python-ldap-test/pull/15 to resolve it.

Crude, but effective.

For folks interested in finding a more elegant solution, running the tests through tox, as the original authors intended, seem to work just fine.  Very strange.

**Comment by zoldar** [comment]
The fix got released:

https://pypi.python.org/pypi/python-ldap-test/0.3.1

Again, thank you for your contribution @nikogura  

Closing.
