### ISSUE TITLE
obscure error when java can't be found

### ISSUE THREAD

**Issue by filippog** [zoldar/python-ldap-test#6]
hi,
I was running python-ldap-test on a brand new machine without java installed, the error displayed is `/bin/sh: 1: exec: None: not found` but no exception, and indeed this is what is being tried
```
[pid  3056] execve("/bin/sh", ["/bin/sh", "-c", "exec None -jar /home/godog/src/a"...], [/* 4 vars */]) = 0
```

**Comment by zoldar** [comment]
Thank you for reporting that issue @filippog. I have made a new release (0.2.1) with additional check and more informative exception.

**Comment by filippog** [comment]
thanks @zoldar that was quick!
