### ISSUE TITLE
0.2.1 not avaliable via pypi

### ISSUE THREAD

**Issue by pyther** [zoldar/python-ldap-test#7]
On the pypi page there is no download button
https://pypi.python.org/pypi/python-ldap-test/

pip is looking at https://pypi.python.org/simple/python-ldap-test/ and as you can see 0.2.1 isn't listed.

**Comment by zoldar** [comment]
I have botched the last release. The new release script was missing the actual upload step, duh. Fixed. Thanks for the heads up @pyther !
